# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c59836cca4cb45f7b6bc49d63e15f01e4e10ac3312a2fbf825e447d5498f6d5700b9d4cb624a6d4a4e4ef998949d31cae6cba1a6459972ba1dfcd514c70ab71

test:
  secret_key_base: eaa5b39a875fa9bc792d5fa67fdf8dca2b08fec1724ec747a80d864d6fc56df58cd57c0ffb6101d040cdcb6213a3648b0e0a1cfe23a1b106e20e36c9c6fd6e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
